# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-14 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='importance',
            field=models.CharField(choices=[('1', 'just a drop in the bucket'), ('2', 'big deal'), ('3', 'milestone in your life')], default='1', max_length=1),
        ),
    ]
