# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-15 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_importance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, default='task description not available', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='importance',
            field=models.CharField(choices=[('1', 'just a drop in the bucket'), ('2', 'big deal'), ('3', 'milestone in your life')], default='just a drop in the bucket', max_length=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='short_command',
            field=models.CharField(max_length=30, verbose_name='task'),
        ),
    ]
