# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-23 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20160718_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='importance',
            field=models.CharField(choices=[('1', 'low'), ('2', 'normal'), ('3', 'high')], default='just a drop in the bucket', max_length=1),
        ),
    ]
